# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comictitle',
            name='Publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pullhold.Publisher'),
        ),
    ]
