# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullhold', '0002_comictitle_reservations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comictitle',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='comictitle',
            name='comic_title',
            field=models.CharField(max_length=75),
        ),
    ]
