# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pullhold', '0003_auto_20170630_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pullhold.ComicTitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
