# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pullhold', '0005_comictitle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullhold',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='pullhold',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comictitle',
            name='user',
        ),
        migrations.DeleteModel(
            name='PullHold',
        ),
    ]
