# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullhold', '0009_auto_20170705_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comictitle',
            name='readers',
            field=models.ManyToManyField(to='pullhold.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comics',
            field=models.ManyToManyField(related_name='pullhold_list', to='pullhold.ComicTitle'),
        ),
    ]
