# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pullhold', '0010_auto_20170709_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comictitle',
            name='readers',
        ),
    ]
