# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullhold', '0011_remove_comictitle_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comictitle',
            name='readers',
            field=models.ManyToManyField(to='pullhold.UserProfile'),
        ),
    ]
