# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullhold', '0012_comictitle_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comictitle',
            name='readers',
            field=models.ManyToManyField(blank=True, to='pullhold.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comics',
            field=models.ManyToManyField(blank=True, related_name='pullhold_list', to='pullhold.ComicTitle'),
        ),
    ]
