# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullhold', '0016_auto_20170712_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comictitle',
            name='cover_art',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
